// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Citadely | Open Access AI Vault",
//   description: "Professional-grade AI prompts for students.",
//   metadataBase: new URL('https://citadely.net'), // 👈 Update this
//   openGraph: {
//     title: "Citadely AI Vault",
//     description: "Unlock 50+ AI Study Prompts",
//     url: "https://citadely.net", // 👈 Update this
//     siteName: "Citadely",
//   },
// };


export const metadata: Metadata = {
  title: "50 Free AI Prompts for Students | Citadely",
  description: "50 free AI prompts to help you outline essays, summarize notes, and prep for exams faster. Works with ChatGPT, Claude, Gemini, and more.",
  openGraph: {
    title: "50 Free AI Prompts for Students",
    description: "Copy, paste, done. 50 free prompts for essays, research, and exam prep.",
    url: "https://www.citadely.net/vault/study-prompts",
    siteName: "Citadely",
    images: [
      {
        url: "https://www.citadely.net/og-image.png",
        width: 1200,
        height: 630,
        alt: "50 AI Prompts for Students",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "50 Free AI Prompts for Students",
    description: "Copy, paste, done. 50 free prompts for essays, research, and exam prep.",
    images: ["https://www.citadely.net/og-image.png"],
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col bg-white">
          {/* Header is now global */}
          <Header />
          
          {/* This is where each individual page content is injected */}
          <main className="flex-grow">
            {children}
          </main>

          {/* Footer is now global */}
          <Footer />
        </div>
      </body>
    </html>
  );
}