// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/layout/header";
// import Footer from "@/components/layout/footer";

// const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
//   title: "Citadely",
//   description: "Free resources and guides.",
//   verification: {
//     other: {
//       "impact-site-verification": ["fd132833-fb8d-4a74-ade4-f0b357ee9a1e"],
//     },
//   },
// };


// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="min-h-screen flex flex-col bg-white">
//           {/* Header is now global */}
//           <Header />
          
//           {/* This is where each individual page content is injected */}
//           <main className="flex-grow">
//             {children}
//           </main>

//           {/* Footer is now global */}
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }



// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Citadely",
//   description: "Free resources and guides.",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

// src/app/layout.tsx

export const metadata: Metadata = {
  title: "Citadely | 50 Free AI Prompts for Students",
  description: "Download the ultimate AI prompt vault. Save 20+ hours of study time and start earning in USD.",
  openGraph: {
    title: "Citadely | 50 Free AI Prompts for Students",
    description: "Get the professional-grade AI toolkits for students. 100% Free Download.",
    url: "https://www.citadely.net",
    siteName: "Citadely",
    images: [
      {
        url: "https://www.citadely.net/og/study-prompts.png", // Use the path to your best prompt image
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    images: ["https://www.citadely.net/og/study-prompts.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
  
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col bg-white">
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}